# Generated by Django 4.1.7 on 2023-03-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinfind',
            name='pesquisas',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
