# Generated by Django 4.1.7 on 2023-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchcoin', '0002_alter_coinfind_pesquisas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinfind',
            name='pesquisas',
            field=models.IntegerField(default=0),
        ),
    ]
