# Generated by Django 4.1.7 on 2023-03-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcj', '0002_alter_buyconcj_options_alter_coincj_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coincj',
            name='product',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='coincj',
            name='qnt',
            field=models.IntegerField(default=0, verbose_name='Quantidade Pesquisa'),
        ),
    ]
